language: php

services:
  - mysql

php:
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - echo "127.0.0.1" > /etc/hosts
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install

script:
  - vendor/bin/grumphp run
