language: php

services:
  - mysql

php:
  - 5.6

addons:
  hosts:
    - mysql

  - mysql -u root -e "SET GLOBAL sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'"
  - mysql -u root -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;"
  - travis_retry composer self-update
  - travis_retry composer update $PREFER_LOWEST
  - composer install

script:
  - vendor/bin/phpcs -p ./src --standard=PHPCompatibility,PSR2 --runtime-set testVersion 5.3
  - vendor/bin/phpcs -p ./src --standard=PHPCompatibility,PSR2 --runtime-set testVersion 5.4
  - vendor/bin/phpcs -p ./src --standard=PHPCompatibility,PSR2 --runtime-set testVersion 5.5
  - vendor/bin/phpcs -p ./src --standard=PHPCompatibility,PSR2 --runtime-set testVersion 5.6
  - vendor/bin/behat
